stages:
  - test-execution

automated-tests-execution:
  stage: test-execution
  image: gradle:latest
  variables:
    TESTS_FOLDER: "src/test/resources/features"
  artifacts:
    paths:
      - $TESTS_FOLDER/output
    when: always
    expire_in: 1 week
  script:
    - cd $TESTS_FOLDER
    - gradle test
