stages:
  - test-execution

automated-tests-execution:
  stage: test-execution
  image: node:latest
  variables:
    TESTS_FOLDER: "./automated-tests"
  artifacts:
    paths:
      - $TESTS_FOLDER/output/
    when: always
    expire_in: 1 week
  script:
    - cd $TESTS_FOLDER
    - yarn cucumber-js -p test features/
